<?php

namespace AppBundle\Repository;

/**
 * DirectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectorRepository extends \Doctrine\ORM\EntityRepository
{
}
