# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: email
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/admin, roles: "ROLE_ADMIN" }
        - { path: ^/home, roles: "ROLE_USER" }
